### ISSUE TITLE
Update Fast Egg Hatch for 2.0.2

### ISSUE THREAD

**Issue by Bniccs** [Eppin/Sysbot.NET#17]
Hi, 

Is it possible for you to update support for the fast egg hatch for 2.0.2?

Many thanks

**Comment by Eppin** [comment]
Thanks for creating an issue. Currently I've no plans of upgrading for 2.0.2 as the new DLC is around the corner (and none of my CFW console run 2.0.2). As soon as it drops, I'll have support for it.
