### ISSUE TITLE
Stop Condition Filter for Gender

### ISSUE THREAD

**Issue by TheChaotician** [Eppin/Sysbot.NET#7]
**All tested features of the bot work fine**

I’m looking to breed female Pokémon to avoid infatuation from Cute Charm Enamorus.

I seem to recall that a filter for gender was present in a previous version, either that or I’m extremely lucky!

Couldn’t find the option in the gui or config.json. Also couldn’t find you on Discord so apologies for cluttering your GitHub repo!

**Comment by Eppin** [comment]
Hi! I'll have a look, it could be gone missing due to a change in the fork. It used to be based of another fork, but recently I changed it. Because there was some code I didn't want to support/maintain.

I'll keep you posted!

**Comment by TheChaotician** [comment]
Thanks for your response! I’ll see if I can find you on Discord :)

No other issues - the bot does everything I want and some! Many thanks for your hard work!

**Comment by Eppin** [comment]
Fixed and new release will be made :-)
